# Generated by Django 5.2.8 on 2025-11-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('cpu', models.CharField(max_length=128)),
                ('mem', models.CharField(max_length=128)),
                ('disk', models.CharField(max_length=128)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
            },
        ),
    ]
